spring:
  application:
    name: mini-fdu-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # whether to allow cookies to cross domains
            allowCredentials: true
            # urls that are allowed to cross domains, * for all urls
            allowedOriginPatterns: '*'
            # methods that are allowed to cross domains, * for all methods
            allowedMethods: '*'
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-Requested-With
            # cross region preflight time
            maxAge: 3600
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_IP:127.0.0.1}:${USER_SERVICE_PORT:8799}
          predicates:
            - Path=/user-service/**
        - id: message-service
          uri: http://${MESSAGE_SERVICE_IP:127.0.0.1}:${MESSAGE_SERVICE_PORT:8798}
          predicates:
            - Path=/message-service/**
        - id: chat-service
          uri: ws://${CHAT_SERVICE_IP:127.0.0.1}:${CHAT_SERVICE_PORT:8798}
          predicates:
            - Path=/chat/**
        - id: game-service
          uri: ws://${GAME_SERVICE_IP:127.0.0.1}:${GAME_SERVICE_PORT:8798}
          predicates:
            - Path=/game/**
        - id: video-chat-service
          uri: ws://${VIDEO_CHAT_SERVICE_IP:127.0.0.1}:${VIDEO_CHAT_SERVICE_PORT:8798}
          predicates:
            - Path=/video-chat/**
        - id: study-service
          uri: http://${STUDY_SERVICE_IP:127.0.0.1}:${STUDY_SERVICE_PORT:8797}
          predicates:
            - Path=/study-service/**
        - id: ai-service
          uri: http://${AI_SERVICE_IP:127.0.0.1}:${AI_SERVICE_PORT:8796}
          predicates:
            - Path=/AI-service/**
server:
  port: ${SERVER_PORT:8700}